### ISSUE TITLE
Problems in git pull script

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/backend#109]
2020-03-03 18:46:08 ERROR    flask.app => Exception on /check-platform-metadata [POST] - 1761
Traceback (most recent call last):
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yang/backend/lib/python3.4/site-packages/Flask_Cors-3.0.7-py3.4.egg/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yang/backend/lib/python3.4/site-packages/yang-0.0.0-py3.4.egg/api/yangCatalogApi.py", line 2460, in trigger_populate
    repoutil.pull(application.yang_models)
  File "/home/yang/backend/lib/python3.4/site-packages/yang-0.0.0-py3.4.egg/utility/repoutil.py", line 66, in pull
    s.update(recursive=True, init=True)
  File "/home/yang/backend/lib/python3.4/site-packages/GitPython-2.1.11-py3.4.egg/git/objects/submodule/base.py", line 640, in update
    force=force, keep_going=keep_going)
  File "/home/yang/backend/lib/python3.4/site-packages/GitPython-2.1.11-py3.4.egg/git/objects/submodule/base.py", line 494, in update
    remote.fetch(progress=progress)
  File "/home/yang/backend/lib/python3.4/site-packages/GitPython-2.1.11-py3.4.egg/git/remote.py", line 789, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/home/yang/backend/lib/python3.4/site-packages/GitPython-2.1.11-py3.4.egg/git/remote.py", line 706, in _get_fetch_info_from_stderr
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/home/yang/backend/lib/python3.4/site-packages/GitPython-2.1.11-py3.4.egg/git/remote.py", line 706, in <genexpr>
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/home/yang/backend/lib/python3.4/site-packages/GitPython-2.1.11-py3.4.egg/git/remote.py", line 325, in _from_line
    old_commit = repo.rev_parse(operation.split(split_token)[0])
  File "/home/yang/backend/lib/python3.4/site-packages/GitPython-2.1.11-py3.4.egg/git/repo/fun.py", line 334, in rev_parse
    obj = name_to_object(repo, rev)
  File "/home/yang/backend/lib/python3.4/site-packages/GitPython-2.1.11-py3.4.egg/git/repo/fun.py", line 147, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref '9e367b6' did not resolve to an object

**Comment by miroslavKovacPantheon** [comment]
Git was creating fork with suffix and this has been resolved
