### ISSUE TITLE
Crash in populate.py

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#422]
Steps to reproduce:
1. open a shell in the backend container
2. cd into the parseAndPopulate directory
3. run `python3 populate.py --dir /var/yang/nonietf/yangmodels/yang/vendor/cisco/xr/751/ --notify-indexing --force-parsing`

backtrace:
```
Traceback (most recent call last):
  File "/backend/parseAndPopulate/populate.py", line 296, in <module>
    main()
  File "/backend/parseAndPopulate/populate.py", line 232, in main
    raise e
  File "/backend/parseAndPopulate/populate.py", line 229, in main
    submodule.main(scriptConf=script_conf)
  File "/backend/lib/python3.9/site-packages/yang-0.0.0-py3.9.egg/parseAndPopulate/runCapabilities.py", line 193, in main
    capability.parse_and_dump_vendor()
  File "/backend/lib/python3.9/site-packages/yang-0.0.0-py3.9.egg/parseAndPopulate/capability.py", line 469, in parse_and_dump_vendor
    schema_part = '{}/{}/{}/{}/'.format(github_raw, self.owner, self.repo, self.branch)
AttributeError: 'Capability' object has no attribute 'owner'
```

**Comment by SlavomirMazurPantheon** [comment]
There is an error in several paths in platform-metadata.json file:
https://github.com/YangModels/yang/blob/fa6a63a76f46442b46e55d7724d6aba50973fba2/vendor/cisco/xr/751/platform-metadata.json#L7
I will create PT to the YangModels/yang repository.
However, we still need to update backend code to handle this and not raise error.
