### ISSUE TITLE
Yang search regex search error

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#541]
Steps to reproduce:
1. go to https://yangcatalog.org/yang-search
2. tick the `Regular Expression` box
3. search for `"test`

The following error is logged
```
2022-07-20 10:22:28 ERROR    app.py api => Exception on /api/yang-search/v2/search [POST] - 1440
Traceback (most recent call last):
  File "/backend/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/backend/lib/python3.9/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/backend/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/backend/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/backend/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/backend/api/views/yangSearch/yangSearch.py", line 261, in search
    response['rows'], response['max-hits'] = elk_search.search()
  File "/backend/api/views/yangSearch/elkSearch.py", line 179, in search
    self._resolve_aggregations()
  File "/backend/api/views/yangSearch/elkSearch.py", line 275, in _resolve_aggregations
    response = self._es_manager.generic_search(ESIndices.YINDEX, self.query)
  File "/backend/elasticsearchIndexing/es_manager.py", line 285, in generic_search
    return self.es.search(index=index.value, body=query, request_timeout=self.elk_request_timeout,
  File "/backend/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/backend/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 1658, in search
    return self.transport.perform_request(
  File "/backend/lib/python3.9/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/backend/lib/python3.9/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/backend/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/backend/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 315, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: expected \'"\' at position 3')
```
I think this is probably an input sanitization issue. There is no error if the input contains an even number of double quotes. There might be other characters that trigger this issue.

**Comment by SlavomirMazurPantheon** [comment]
First of all, we need to add some [validation to the UI](https://github.com/YangCatalog/yangcatalog-ui/issues/97). If user wants to search by Regex expression we need to check whether this expression is actually valid BEFORE sending it to the backend.

However, this particular regex: `"test` seems to be valid regex so we also need to add some check to the backend too.
I think that in this case we can either escape this character or remove it from searched term completely.
