### ISSUE TITLE
Sender.py should wait until RabbitMQ is up and running

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/backend#57]
At least in api/sender.py, there is a race condition when Linux reboots: RabbitMQ takes longer to start than UWSGI, so, the initialization code should wait until RabbitMQ is running by handling the exception rather than exiting.

```
uwsgi socket 0 bound to TCP address :8443 fd 10
Python version: 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC]
Set PythonHome to /home/yang/backend
Python main interpreter initialized at 0x1d8af10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 537088 bytes (524 KB) for 20 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "./wsgi.py", line 23, in <module>
    from api.yangCatalogApi import application
  File "/home/yang/backend/lib/python3.4/site-packages/yang-0.0.0-py3.4.egg/api/yangCatalogApi.py", line 365, in <module>
    application = MyFlask(__name__)
  File "/home/yang/backend/lib/python3.4/site-packages/yang-0.0.0-py3.4.egg/api/yangCatalogApi.py", line 131, in __init__
    self.sender = Sender(log_directory, self.temp_dir)
  File "/home/yang/backend/lib/python3.4/site-packages/yang-0.0.0-py3.4.egg/api/sender.py", line 50, in __init__
    pika.ConnectionParameters('127.0.0.1', heartbeat=0))
  File "/usr/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/usr/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 417, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 471, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
pika.exceptions.ConnectionClosed: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by evyncke** [comment]
Actually, all calls to interact with RabbitMQ should handle RabbitMQ being down as RabbitMQ could itself be crashed and restarting...

**Comment by evyncke** [comment]
This should be fixed now by retrying every minute until success at the first connection.

But, unsure what will happen if the RabbitMQ server fails while the backend API daemon still works

**Comment by miroslavKovacPantheon** [comment]
The same is done in docker container environement. I keep restarting receiver until rabbitmq is up and running. Also checking if rabbitmq is healthy. I would close this since this is implemented in both server and docker-compose file. Would you agree @evyncke
