### ISSUE TITLE
Error populating IANA modules

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#629]
This error seems to be triggered on every run of the draftPullLocal.py script after draft and rfc modules have been populated.
```
2022-10-09 22:06:40 ERROR    draftPullLocal.py draftPullLocal => Error occurred while running populate.py script - 80
Traceback (most recent call last):
  File "/backend/ietfYangDraftPull/draftPullLocal.py", line 78, in run_populate_script
    submodule.main(script_conf=script_conf)
  File "/backend/parseAndPopulate/populate.py", line 322, in main
    Populate(script_conf.args, config, message_factory=message_factory).start_populating()
  File "/backend/parseAndPopulate/populate.py", line 183, in start_populating
    self._run_parse_directory_script()
  File "/backend/parseAndPopulate/populate.py", line 236, in _run_parse_directory_script
    raise e
  File "/backend/parseAndPopulate/populate.py", line 233, in _run_parse_directory_script
    parse_directory.main(script_conf=script_conf)
  File "/backend/parseAndPopulate/parse_directory.py", line 135, in main
    parse_sdo(args.dir, dumper, file_hasher, args.api, dir_paths, path_to_name_rev, LOGGER)
  File "/backend/parseAndPopulate/parse_directory.py", line 190, in parse_sdo
    grouping.parse_and_load()
  File "/backend/parseAndPopulate/groupings.py", line 319, in parse_and_load
    name, revision = self.path_to_name_rev[path]
KeyError: '/var/yang/tmp/draftpulllocal/standard/iana/iana-if-type@2022-08-24.yang'
```

**Comment by richardzilincikPantheon** [comment]
Seems to be caused by inconsistent data in https://github.com/YangModels/yang/tree/main/standard/iana, the xml specifies a revision that isn't present in the directory.

**Comment by richardzilincikPantheon** [comment]
`ianaPull.log` contains this probably related message
```
2022-10-11 14:05:06 WARNING  draftPullUtility.py ianaPull => yang-catalog/yang repo might not be up-to-date - 261
```

**Comment by SlavomirMazurPantheon** [comment]
Some iana-if-types revisions are excluded, because pushing them into YangModels/yang repo would cause Github Actions run failure. See content of `/var/yang/ietf-exceptions/iana-exceptions.dat` file.

**Comment by richardzilincikPantheon** [comment]
Yes looks like that's the issue, the exceptions aren't checked when trying to parse modules.
