### ISSUE TITLE
ES deletion timeout

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#632]
Two similar errors found in `process-changed-mods.log`.
```
2022-10-08 08:13:58 ERROR    build_yindex.py process_changed_mods => module Cisco-IOS-XR-ipv4-hsrp-oper-sub1@2022-03-24 timed out too many times failing - 114
[...]
Traceback (most recent call last):
  File "/backend/elasticsearchIndexing/build_yindex.py", line 80, in build_indices
    es_manager.delete_from_indices(module)
  File "/backend/elasticsearchIndexing/es_manager.py", line 166, in delete_from_indices
    self.delete_from_index(index, module)
  File "/backend/elasticsearchIndexing/es_manager.py", line 162, in delete_from_index
    return self.es.delete_by_query(index=index.value, body=delete_module_query, conflicts='proceed')
  File "/backend/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/backend/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 722, in delete_by_query
    return self.transport.perform_request(
  File "/backend/lib/python3.9/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/backend/lib/python3.9/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/backend/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPSConnectionPool(host='vpc-yc-elk-production-ykorid5flzyl6zwre5bvmyypvq.us-east-2.es.amazonaws.com', port='443'): Read timed out. (read timeout=10))

2022-10-08 08:13:58 ERROR    process-changed-mods.py process_changed_mods => Problem while processing module Cisco-IOS-XR-ipv4-hsrp-oper-sub1@2022-03-24/cisco - 163
[...]
Traceback (most recent call last):
  File "/backend/elasticsearchIndexing/process-changed-mods.py", line 161, in _change_modules_in_es
    build_indices(self.es_manager, module, self.save_file_dir, self.json_ytree, self.logger)
  File "/backend/elasticsearchIndexing/build_yindex.py", line 115, in build_indices
    raise e
  File "/backend/elasticsearchIndexing/build_yindex.py", line 80, in build_indices
    es_manager.delete_from_indices(module)
  File "/backend/elasticsearchIndexing/es_manager.py", line 166, in delete_from_indices
    self.delete_from_index(index, module)
  File "/backend/elasticsearchIndexing/es_manager.py", line 162, in delete_from_index
    return self.es.delete_by_query(index=index.value, body=delete_module_query, conflicts='proceed')
  File "/backend/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/backend/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 722, in delete_by_query
    return self.transport.perform_request(
  File "/backend/lib/python3.9/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/backend/lib/python3.9/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/backend/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPSConnectionPool(host='vpc-yc-elk-production-ykorid5flzyl6zwre5bvmyypvq.us-east-2.es.amazonaws.com', port='443'): Read timed out. (read timeout=10))
```
The errors happen for `Cisco-IOS-XR-ipv4-hsrp-oper-sub1@2022-03-24` and `Cisco-IOS-XR-ipv4-hsrp-oper@2022-03-24`.

**Comment by richardzilincikPantheon** [comment]
This issue seems to be resolved. The errors no longer appear in recent logs and both of the modules get indexed successfully in my local environment.
