### ISSUE TITLE
Impact analysis attempting to search for modules not in ES

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#633]
```
2022-10-07 10:25:13 ERROR    yangSearch.py yang-search => Failed to get revisions and organization for flexible-encapsulation - 501
Traceback (most recent call last):
  File "/backend/api/views/yangSearch/yangSearch.py", line 493, in get_modules_revision_organization
    organization = hits[0]['_source']['organization']
IndexError: list index out of range
2022-10-07 10:25:13 ERROR    yangSearch.py yang-search => Failed to get revisions and organization for if-l3-vlan - 501
Traceback (most recent call last):
  File "/backend/api/views/yangSearch/yangSearch.py", line 493, in get_modules_revision_organization
    organization = hits[0]['_source']['organization']
IndexError: list index out of range
```
I'm guessing these modules are listed as dependents for some other modules, but for some reason they're not available in ES. Both of these modules are from archived Internet Drafts. @SlavomirMazurPantheon am I right in thinking all modules from archived drafts are supposed to be present in YC?

**Comment by richardzilincikPantheon** [comment]
This happens when dependents of these modules are looked up in impact anaysis. Instead of looking these modules up directly, the endpoints used by impact analysis should check if the module is listed in `unparsable-modules.json`.
