### ISSUE TITLE
Cisco-IOS-XE-wireless-access-point-oper returns 500 

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/backend#97]
serch for module Cisco-IOS-XE-wireless-access-point-oper,2018-06-28,cisco fails with 500 code. with error message

2019-09-02 04:19:24 ERROR    flask.app => Exception on /search/modules/Cisco-IOS-XE-wireless-access-point-oper,2018-06-28,cisco [GET] - 1761
Traceback (most recent call last):
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yang/backend/lib/python3.4/site-packages/Flask_Cors-3.0.7-py3.4.egg/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yang/backend/lib/python3.4/site-packages/Flask-1.0.2-py3.4.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yang/backend/lib/python3.4/site-packages/yang-0.0.0-py3.4.egg/api/yangCatalogApi.py", line 2315, in search_module
    'cache_modules{}'.format(active_cache[1]))\
AttributeError: 'NoneType' object has no attribute 'decode'

This could happen with multiple modules but I haven t seen this with any other except this one yet

**Comment by miroslavKovacPantheon** [comment]
Tested if the module is cached at the startup and it is correctly. I can see the module being saved to cache with correct key. when getting module out of cache using key I am receiving None.

**Comment by miroslavKovacPantheon** [comment]
This was maintenance issue. we run out of uwsgi preset cache memory. I ll update yang-catalog.ini-dist file as well just to make obvious that catalog got bigger and we need more RAM for uwsgi.
